### ISSUE TITLE
InitialiseFields break

### ISSUE THREAD

**Issue by fb-multimedia** [jaheyns/CfdOF#24]
Hello,
First I would thank you for all your effort in this project.
I'm beginner in Freecad and CFD.
 I've try make a very simple case with cube and a cylindre add cfd analysis but when I clic "InitialiseFields" button This error appear :
`Traceback (most recent call last):
  File "/home/fred/.FreeCAD/Mod/CfdOF/CfdInitialiseFlowField.py", line 149, in setEdit
    self.Object, physics_model, boundaries, material_objs)
  File "/home/fred/.FreeCAD/Mod/CfdOF/_TaskPanelCfdInitialiseInternalFlowField.py", line 62, in __init__
    self.load()
  File "/home/fred/.FreeCAD/Mod/CfdOF/_TaskPanelCfdInitialiseInternalFlowField.py", line 104, in load
    self.form.comboInlets.setCurrentIndex(self.form.comboInlets.findData(self.obj.Inlet.Name))
<class 'AttributeError'>: 'NoneType' object has no attribute 'Name'
`
and the task dialog doesn't show.
Thanks for your help.

**Comment by oliveroxtoby** [comment]
Oops! Thank you for reporting. Should be fixed.

**Comment by fb-multimedia** [comment]
Thanks a lot !
