### ISSUE TITLE
Error on run mesher

### ISSUE THREAD

**Issue by alexbhandari** [jaheyns/CfdOF#38]
I am having issues running the mesher on windows and getting the below error. It looks like the mesh case is created fine, but the directory is not accessible in openfoam because it is outside the docker instance. 

![image](https://user-images.githubusercontent.com/3032338/88445610-5e37a300-cde9-11ea-978f-7bfe93de8d30.png)

FreeCAD info:
```
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

I have installed openfoam from the preferences. I cannot run the dependency checker though as this hangs for me. That may be a separate bug I am thinking
![image](https://user-images.githubusercontent.com/3032338/88448342-6fd97480-ce02-11ea-9a67-c297250419bf.png)

**Comment by alexbhandari** [comment]
Some more info

Python output
```
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> MRU="0"
>>> exec(open('C:/Program Files/FreeCAD 0.18/data/Mod/Start/StartPage/LoadMRU.py').read())
>>> App.setActiveDocument("air_curtainV2_cfd")
>>> App.ActiveDocument=App.getDocument("air_curtainV2_cfd")
>>> Gui.ActiveDocument=Gui.getDocument("air_curtainV2_cfd")
>>> App.getDocument("air_curtainV2_cfd").removeObject("SubtractivePipe_Mesh")
>>> App.getDocument("air_curtainV2_cfd").recompute()
>>> Gui.activateWorkbench("CfdOFWorkbench")
>>> 
>>> import CfdMesh
>>> CfdMesh.makeCfdMesh('SubtractivePipe_Mesh')
>>> App.ActiveDocument.ActiveObject.Part = App.ActiveDocument.SubtractivePipe
>>> import CfdTools
>>> CfdTools.getActiveAnalysis().addObject(App.ActiveDocument.ActiveObject)
>>> 
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.CharacteristicLengthMax = '0 mm'
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.MeshUtility = 'cfMesh'
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.ElementDimension = '3D'
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.CellsBetweenLevels = 3
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.EdgeRefinement = 1.0
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.PointInMesh = {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}
>>> import CfdMeshTools
>>> FreeCAD.ActiveDocument.SubtractivePipe_Mesh.Proxy.cart_mesh = CfdMeshTools.CfdMeshTools(FreeCAD.ActiveDocument.SubtractivePipe_Mesh)
>>> cart_mesh = FreeCAD.ActiveDocument.SubtractivePipe_Mesh.Proxy.cart_mesh
>>> cart_mesh.processDimension()
>>> cart_mesh.getFilePaths(CfdTools.getOutputPath(FreeCAD.ActiveDocument.CfdAnalysis))
>>> cart_mesh.setupMeshCaseDir()
>>> cart_mesh.processRefinements()
>>> cart_mesh.writeMeshCase()
>>> cart_mesh.writePartFile()
>>> 
```

Report view output
```
Part to mesh:
  Name: SubtractivePipe, Label: SubtractivePipe, ShapeType: Solid
  CharacteristicLengthMax: 3.2865659918281955
  ElementDimension: 3D
  No mesh refinement
Populating mesh dictionaries in folder C:\Users\<username>\AppData\Local\Temp\meshCase
Successfully wrote meshCase to folder C:\Users\<username>\AppData\Local\Temp\meshCase
Triangulating part: SubtractivePipe:face0 ... writing to file
Triangulating part: SubtractivePipe:face1 ... writing to file
Triangulating part: SubtractivePipe:face2 ... writing to file
Triangulating part: SubtractivePipe:face3 ... writing to file
Triangulating part: SubtractivePipe:face4 ... writing to file
Triangulating part: SubtractivePipe:face5 ... writing to file
Triangulating part: SubtractivePipe:face6 ... writing to file
Triangulating part: SubtractivePipe:face7 ... writing to file
Triangulating part: SubtractivePipe:face8 ... writing to file
Triangulating part: SubtractivePipe:face9 ... writing to file
Triangulating part: SubtractivePipe:face10 ... writing to file
Triangulating part: SubtractivePipe:face11 ... writing to file
Triangulating part: SubtractivePipe:face12 ... writing to file
Triangulating part: SubtractivePipe:face13 ... writing to file
Triangulating part: SubtractivePipe:face14 ... writing to file
Triangulating part: SubtractivePipe:face15 ... writing to file
Triangulating part: SubtractivePipe:face16 ... writing to file
Triangulating part: SubtractivePipe:face17 ... writing to file
Triangulating part: SubtractivePipe:face18 ... writing to file
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\FreeCAD\Mod\CfdOF\_TaskPanelCfdMesh.py", line 230, in runMesh
    cmd = CfdTools.makeRunCommand('./Allmesh', cart_mesh.meshCaseDir, source_env=False)
  File "C:\Users\<username>\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdTools.py", line 582, in makeRunCommand
    cd = 'cd "{}" && '.format(translatePath(dir))
  File "C:\Users\<username>\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdTools.py", line 448, in translatePath
    return fromWindowsPath(p)
  File "C:\Users\<username>\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdTools.py", line 478, in fromWindowsPath
    raise ValueError("The path {} is not inside the users's home directory.".format(p))
ValueError: The path C:\Users\<username>\AppData\Local\Temp\meshCase is not inside the users's home directory.
```

**Comment by alexbhandari** [comment]
moving this to forum - missed guidelines saying to post in forum first so closing this issue
