### ISSUE TITLE
Set initialization zone results in exception

### ISSUE THREAD

**Issue by oliveroxtoby** [jaheyns/CfdOF#92]
In GitLab by @icojb25 on May 20, 2022, 04:18

On develop: Trying a multiphase problem with initialization zone - clicking Initialization Zone results in:

16:13:46  Traceback (most recent call last):
  File "C:\Users\bergh\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdZone.py", line 251, in setEdit
    taskd = _TaskPanelCfdZone._TaskPanelCfdZone(self.Object)
  File "C:\Users\bergh\AppData\Roaming\FreeCAD\Mod\CfdOF\_TaskPanelCfdZone.py", line 46, in __init__
    self.NeedsCaseRewriteOrig = self.analysis_obj.NeedsCaseRewrite
<class 'AttributeError'>: '_TaskPanelCfdZone' object has no attribute 'analysis_obj'

I have not done multiphase with the tool before so I am not sure of the procedure, but the Analysis / BC's / Mesh / fluid props / Physics are all set. I have multiple fluids set (air, water). Not sure if this is related to the new detection feature perhaps?

**Comment by oliveroxtoby** [comment]
In GitLab by @oliveroxtoby on May 22, 2022, 19:06

mentioned in commit a07ab27d34e2f000cf9f3c9862a0c7b1868a363d

**Comment by oliveroxtoby** [comment]
In GitLab by @oliveroxtoby on May 22, 2022, 19:09

My bad. Thanks for reporting!
